### ISSUE TITLE
.NET Core Class Library project templates are not available in Blend's New Project dialog

### ISSUE THREAD

**Issue by debonte** [dotnet/templates#124]
**Repro:**
1. Install .NET Core 3.0 SDK
2. Start Blend 2019
3. Press the "Create a new project..." button
4. Search for "class library core"

**Expected:** The C# and VB "Class Library (.NET Core)" templates appear.

**Actual:** No matching templates are found.

**Comment by debonte** [comment]
Although there are .NET Framework project templates that create WPF-compatible libraries (ex. WPF User Control Library), there's nothing similar for .NET Core yet. The workaround at this point is to create a .NET Core Class Library and modify it by changing the Sdk to Microsoft.NET.Sdk.WindowsDesktop and setting the UseWPF property to true.

**Comment by jmarolf** [comment]
Thanks for this!  I'll take a look and see what is blocking the .NET Core templates from appearing.  @debonte did you install any of the .NET Core workloads? I guess more specifically, in order to help me narrow this down, which workloads do you have installed?

**Comment by debonte** [comment]
Sorry, I guess I should have mentioned up front that I already had a fix for this. Didn't realize you'd see it so quickly. :)

**Comment by jmarolf** [comment]
@debonte I see that now.  I'll talk to you on the PR.

**Comment by debonte** [comment]
Verified that this is fixed in recent internal VS builds. I used d16.2stg 28929.422.
