### ISSUE TITLE
VB .NET Core desktop templates are filtered out when Language=VisualBasic in New Project dialog

### ISSUE THREAD

**Issue by debonte** [dotnet/templates#126]
1. Start VS or Blend
2. Press "Create a new project" button
3. Select "Visual Basic" in the Language combo box at the top of the New Project dialog
4. Enter "wpf core" in the search box

**Expected:** "WPF App (.NET Core)" VB template is shown.

**Actual:** No matches found. But if you change Language to "All Languages" you'll see both of the "WPF App (.NET Core)" templates -- C# and VB.

Looks like there's no associated metadata. See the attached screenshot. The C# template has "C#", "Windows", and "Desktop" tags on it. The VB template doesn't have any.

WinForms has the same issue -- VS only though since Blend doesn't support WinForms.
![WpfCoreTemplates](https://user-images.githubusercontent.com/12820898/58137054-74deda80-7be5-11e9-8639-5f889f12e35e.PNG)

**Comment by jmarolf** [comment]
I believe this internal PR will fix this problem: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/182449?_a=overview

**Comment by debonte** [comment]
Thanks @jmarolf. I confirmed that this is working in more recent VS builds.
