### ISSUE TITLE
.NET Core WPF project template is not available in Blend's New Project dialog

### ISSUE THREAD

**Issue by debonte** [dotnet/templates#76]
**Repro:**
1. Install .NET Core 3.0 SDK
2. Start Blend 2019
3. Press the "Create new project..." hyperlink

**Expected:** "WPF App (.NET Core)" template appears under the Installed\Visual C#\\.NET Core node in the template tree.

**Actual:** There is no .NET Core node under  Installed\Visual C#, and the "WPF App (.NET Core)" isn't found anywhere else.

**Comment by jmarolf** [comment]
As I mentioned on the PR.  Blend needs to be resilient to the case where these templates are installed but there is no .NET Core SDK and not show these templates in that situation
